[package]
name = "folio"
version = "0.1.0"
description = "A focused WYSIWYG Markdown editor with math, diagrams and local files"
repository = "https://github.com/mozanunal/folio"
homepage = "https://github.com/mozanunal/folio#readme"
keywords = ["markdown", "wysiwyg", "editor", "tauri", "latex"]
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
panic = "abort"
